version: 3

tasks:
  build:
    desc: Build
    cmds:
      - goreleaser build --single-target --snapshot --clean --output dist/go-mjpeg

  outdated:
    desc: Show dependency updates
    aliases: [ dependencyUpdates ]
    cmds:
      - go list -u -m -json all | go-mod-outdated -update -direct

  lint:
    desc: Lint
    cmds:
      - golangci-lint run

  mingo:
    cmds:
      - mingo -tests -v
